Z01R: Nuke unused blobs
error: vendor/asus/Z01R/Android.bp:19689:1: "is_keybox_valid" depends on undefined module "liboemcrypto".
Change-Id: I5117c71f451f12423d271b00f392332da0b7190e